/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package daily_investment.Interfaces;

import Class_Files.AllConfigIsHere;
import Class_Files.Database_Config;
import Class_Files.MessageIcons;
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.util.Calendar;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import org.hibernate.Query;
import org.hibernate.Session;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Ishan Darshana
 */
public class InsertCustomers extends javax.swing.JFrame {

    Database_Config databaseConfig = new Database_Config();
    MessageIcons messageIcons = new MessageIcons();
    AllConfigIsHere allConfigIsHere = new AllConfigIsHere();

    /**
     * Creates new form Customers
     */
    public InsertCustomers() {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource(messageIcons.getFrameIcon())));
        fillNic();
        Location_Rental_Agent();

    }

    //recognize duplicate nic with status P (Processing) 
    boolean recognizeDuplicateNIC() {

        boolean sendTrueOrFalse = false;
        try {
            String sql_00 = "SELECT nic FROM customers WHERE nic= '" + txtNic.getSelectedItem().toString() + "' AND status = 'P' ";
            ResultSet rs_00 = databaseConfig.getStatement().executeQuery(sql_00);
            if (!rs_00.next()) {

                sendTrueOrFalse = false;

            } else {

                sendTrueOrFalse = true;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        return sendTrueOrFalse;

    }

    //Validate customer start date when include wrong input
    boolean dateValidate() {
        try {
            String date = allConfigIsHere.getDateFormat().format(this.j_d_c_Date.getDate());
            return false;
        } catch (Exception e) {

            return true;
        }

    }

    void fillNic() {
        try {

            //add nic to combobox while opening jframe
            String sql_03 = "SELECT nic FROM customers";
            ResultSet rs_03 = databaseConfig.getStatement().executeQuery(sql_03);
            while (rs_03.next()) {

                txtNic.addItem(rs_03.getString("nic"));
                AutoCompleteDecorator.decorate(txtNic);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    void Location_Rental_Agent() {

        try {

            //add locations to combobox
            String sql_00 = "SELECT lineName FROM c_location";
            ResultSet rs_00 = databaseConfig.getStatement().executeQuery(sql_00);
            while (rs_00.next()) {

                txtLineName.addItem(rs_00.getString("lineName"));
                AutoCompleteDecorator.decorate(txtLineName);

            }

            //add rental to combobox
            String sql_01 = "SELECT rental FROM amount";
            ResultSet rs_01 = databaseConfig.getStatement().executeQuery(sql_01);
            while (rs_01.next()) {

                txtRental.addItem(rs_01.getString("rental"));
                AutoCompleteDecorator.decorate(txtRental);

            }

            //add name of Emplyee to combobox
            String sql_02 = "SELECT name FROM employees";
            ResultSet rs_02 = databaseConfig.getStatement().executeQuery(sql_02);
            while (rs_02.next()) {

                kbxAgent.addItem(rs_02.getString("name"));

            }
            // databaseConfig.getConnection().close();
        } catch (Exception e) {
            System.out.println(e);
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        kbxAgent = new javax.swing.JComboBox();
        txtAddress = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTnumber = new javax.swing.JTextField();
        txtLineName = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        j_d_c_Date = new com.toedter.calendar.JDateChooser();
        txtRental = new javax.swing.JComboBox();
        txtNic = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SAVE");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("UPDATE");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("DELETE");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Menu");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Customers");
        setResizable(false);

        kbxAgent.setBackground(new java.awt.Color(204, 204, 204));
        kbxAgent.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        kbxAgent.setMaximumRowCount(2);
        kbxAgent.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Agent" }));
        kbxAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kbxAgentActionPerformed(evt);
            }
        });
        kbxAgent.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                kbxAgentKeyPressed(evt);
            }
        });

        txtAddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        txtAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAddressKeyPressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel10.setText("Agent");

        txtTnumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTnumberActionPerformed(evt);
            }
        });
        txtTnumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTnumberKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTnumberKeyReleased(evt);
            }
        });

        txtLineName.setBackground(new java.awt.Color(204, 204, 204));
        txtLineName.setEditable(true);
        txtLineName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtLineName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLineNameActionPerformed(evt);
            }
        });
        txtLineName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLineNameKeyReleased(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel13.setText("NIC");

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel2.setText("Date");

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel4.setText("Address");

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel5.setText("Telephone");

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel6.setText("Location");

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel8.setText("Rental");

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel11.setText("First Name");

        txtFirstName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFirstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFirstNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFirstNameKeyReleased(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel12.setText("Last Name");

        txtLastName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameActionPerformed(evt);
            }
        });
        txtLastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLastNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLastNameKeyReleased(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("SAVE");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("UPDATE");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setPreferredSize(new java.awt.Dimension(109, 35));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("DELETE");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(255, 51, 51));
        jButton8.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("MENU");
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        j_d_c_Date.setDate(new java.util.Date());

        txtRental.setBackground(new java.awt.Color(204, 204, 204));
        txtRental.setEditable(true);
        txtRental.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRentalActionPerformed(evt);
            }
        });
        txtRental.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRentalKeyReleased(evt);
            }
        });

        txtNic.setBackground(new java.awt.Color(204, 204, 204));
        txtNic.setEditable(true);
        txtNic.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNic.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select or Insert" }));
        txtNic.setPreferredSize(new java.awt.Dimension(88, 23));
        txtNic.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txtNicItemStateChanged(evt);
            }
        });
        txtNic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNicActionPerformed(evt);
            }
        });
        txtNic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNicKeyReleased(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Note", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 13))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel1.setText("<< You can update only Name,Address,Telephone of the Customer.So be careful while inserting new data.");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel3.setText("<< Duplicate NICs are not allowed.But it will allow when Customer status is Finished of that NIC owner.");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel7.setText("<< Last Name and Address is optional.");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel9.setText("<< NIC and Telephone must contains 10 digits.Rental could not be less than zero.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 828, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 828, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 828, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 828, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(299, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(kbxAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j_d_c_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRental, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNic, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLineName, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNic, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLineName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j_d_c_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRental, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(kbxAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(1193, 646));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void kbxAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kbxAgentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kbxAgentActionPerformed

    private void kbxAgentKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kbxAgentKeyPressed

    }//GEN-LAST:event_kbxAgentKeyPressed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtAddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddressKeyPressed

    }//GEN-LAST:event_txtAddressKeyPressed

    private void txtTnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTnumberActionPerformed

    private void txtTnumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTnumberKeyPressed

    }//GEN-LAST:event_txtTnumberKeyPressed

    private void txtTnumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTnumberKeyReleased

    }//GEN-LAST:event_txtTnumberKeyReleased

    private void txtLineNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLineNameActionPerformed

    }//GEN-LAST:event_txtLineNameActionPerformed

    private void txtLineNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLineNameKeyReleased

    }//GEN-LAST:event_txtLineNameKeyReleased

    private void txtFirstNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFirstNameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameKeyPressed

    private void txtFirstNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFirstNameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameKeyReleased

    private void txtLastNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLastNameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameKeyPressed

    private void txtLastNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLastNameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameKeyReleased

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed


    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        try {

            if (txtNic.getSelectedItem() == null || txtNic.getSelectedItem().toString().length() > 10 || txtNic.getSelectedItem().toString().length() < 10) {

                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(null, "Please include 10 digits NIC Number.! ", "Note", JOptionPane.ERROR_MESSAGE, messageIcons.getError());

            } else if (txtFirstName.getText().equals("") || txtLineName.getSelectedItem().toString().equals("")) {

                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(null, "Customer Name & Location is empty.Please include.! ", "Note", JOptionPane.ERROR_MESSAGE, messageIcons.getError());
            } else if (txtTnumber.getText().equals("") || txtTnumber.getText().length() > 10 || txtTnumber.getText().length() < 10) {

                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(null, "Please include 10 digits Telephone Number.! ", "Note", JOptionPane.ERROR_MESSAGE, messageIcons.getError());
            } else if (txtRental.getSelectedItem().equals("") || Double.parseDouble(txtRental.getSelectedItem().toString()) < 0) {

                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(null, "Include correct amount for Rental.It must be more than 0.!  ", "Note", JOptionPane.ERROR_MESSAGE, messageIcons.getError());
            } else if (kbxAgent.getSelectedItem().toString().equals("Select Agent") || kbxAgent.getSelectedItem().toString().equals("")) {

                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(null, "Please Select Agent of Customer.! ", "Note", JOptionPane.ERROR_MESSAGE, messageIcons.getError());

            } else if (dateValidate()) {

                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(null, "Date is Empty or Invalid Format.! ", "Note", JOptionPane.ERROR_MESSAGE, messageIcons.getError());

            } else if (recognizeDuplicateNIC()) {
                
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(null, "Duplication NIC detected.if you really want to add customer belong to this NIC\nchange the NIC and keep it in mind! ", "Note", JOptionPane.ERROR_MESSAGE, messageIcons.getError());


            } else {

                //retrive loan amount from rental
                double loanAmount = Double.parseDouble(txtRental.getSelectedItem().toString()) * 50;
                String sql_10 = "SELECT * FROM amount WHERE loanAmount = " + loanAmount + "";
                ResultSet rs_07 = databaseConfig.getStatement().executeQuery(sql_10);

                if (!rs_07.next()) {

                    //insert new loan amount to amount table
                    String sql_00 = "INSERT INTO amount (loanAmount,rental) VALUES ('" + loanAmount + "',"
                            + "'" + Integer.parseInt(txtRental.getSelectedItem().toString()) + "')";
                    databaseConfig.getStatement().executeUpdate(sql_00);

                }

                //save start date & end date if they not exist
                String startDate = allConfigIsHere.getDateFormat().format(this.j_d_c_Date.getDate());

                String sql_06 = "SELECT startDate FROM Date WHERE startDate = '" + startDate + "'";
                ResultSet rs_04 = databaseConfig.getStatement().executeQuery(sql_06);

                if (!rs_04.next()) {

                    //add 65 to start date to calculate end date
                    Calendar c = Calendar.getInstance();
                    c.setTime(allConfigIsHere.getDateFormat().parse(startDate));
                    c.add(Calendar.DATE, 65);
                    String endDate = allConfigIsHere.getDateFormat().format(c.getTime());
                    //add 65 to start date to calculate end date

                    //insert new date  to date table
                    String sql_00 = "INSERT INTO date (startDate,endDate) VALUES ('" + startDate + "',"
                            + "'" + endDate + "')";

                    databaseConfig.getStatement().executeUpdate(sql_00);

                }

                //save location if not exist
                String sql_03 = "SELECT idLines FROM c_location WHERE lineName = '" + txtLineName.getSelectedItem().toString() + "'";
                ResultSet rs_02 = databaseConfig.getStatement().executeQuery(sql_03);
                

                if (!rs_02.next()) {

                    //insert new location to c_location table
                    String sql_00 = "INSERT INTO c_location (lineName) VALUES ('" + txtLineName.getSelectedItem().toString() + "')";
                    databaseConfig.getStatement().executeUpdate(sql_00);

                }

                //get id of recently added loan amount
                String sql_01 = "SELECT idamount FROM amount WHERE loanAmount = " + loanAmount + "";
                ResultSet rs_00 = databaseConfig.getStatement().executeQuery(sql_01);
                rs_00.first();
                int idAmount = rs_00.getInt("idamount");

                
                //get id of recently added date
                String sql_07 = "SELECT iddate FROM date WHERE startDate = '" + startDate + "'";
                ResultSet rs_05 = databaseConfig.getStatement().executeQuery(sql_07);
                rs_05.first();
                int iddate = rs_05.getInt("iddate");

                //save data to loandetails table
                String sql_08 = "INSERT INTO loandetails (collection,paid,toPaid,totalDays,dayCount,areas,date_iddate,amount_idamount) VALUES ('0'," + 0 + "," + loanAmount / 50 * 65 + ",'0','0','0','" + iddate + "','" + idAmount + "')";
                databaseConfig.getStatement().executeUpdate(sql_08);

                //retrive location from c_location table
                String sql_04 = "SELECT idLines FROM c_location WHERE lineName = '" + txtLineName.getSelectedItem().toString() + "'";
                ResultSet rs_03 = databaseConfig.getStatement().executeQuery(sql_04);
                rs_03.first();
                int idLines = rs_03.getInt("idLines");

                //retrive idEmployees from employees table
                String sql_09 = "SELECT idEmployees FROM employees WHERE name = '" + kbxAgent.getSelectedItem().toString() + "'";
                ResultSet rs_06 = databaseConfig.getStatement().executeQuery(sql_09);
                rs_06.first();
                int idEmployees = rs_06.getInt("idEmployees");

                //get id of loan details table WHERE loan amount = idamount
                String sql_02 = "SELECT idloanDetails FROM loandetails WHERE amount_idamount = " + idAmount + "";
                ResultSet rs_01 = databaseConfig.getStatement().executeQuery(sql_02);
                rs_01.first();
                int IdLoanDetails = rs_01.getInt("idloanDetails");

                //insert all data to customer table
                String sql_05 = "INSERT INTO customers (nic,firstName,lastName,address,contactNumber,status,"
                        + "Lines_idLines,Employees_idEmployees,loanDetails_idloanDetails) VALUES ('" + txtNic.getSelectedItem().toString() + "',"
                        + "'" + txtFirstName.getText() + "','" + txtLastName.getText() + "','" + txtAddress.getText() + "',"
                        + "'" + txtTnumber.getText() + "','P','" + idLines + "','" + idEmployees + "','" + IdLoanDetails + "')";
                databaseConfig.getStatement().executeUpdate(sql_05);

                
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(null, "Record has been successfully added!", "Note", JOptionPane.INFORMATION_MESSAGE, messageIcons.getOk());
            }

        } catch (Exception e) {

            e.printStackTrace();
            System.out.println(e.getMessage());
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        try {

            //update data of customer table
            String sql_00 = "UPDATE customers SET firstName='" + txtFirstName.getText() + "', lastName = "
                    + "'" + txtLastName.getText() + "',address = '" + txtAddress.getText() + "',contactNumber = "
                    + "'" + txtTnumber.getText() + "' WHERE nic = '" + txtNic.getSelectedItem().toString() + "' ";
            databaseConfig.getStatement().executeUpdate(sql_00);
            

            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, "Record has been successfully updated.!", "Note", JOptionPane.INFORMATION_MESSAGE, messageIcons.getOk());

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed


    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        new Menu().menuObject.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void txtRentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRentalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRentalActionPerformed

    private void txtRentalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRentalKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRentalKeyReleased

    private void txtNicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNicActionPerformed

        try {
            //search all data to all textfields from NIC
            String sql = "SELECT cus.firstName,cus.lastName,cus.address,cus.contactNumber,location.lineName,d.startDate,am.rental,emp.name "
                    + "FROM customers cus "
                    + "INNER JOIN c_location location on cus.Lines_idLines = location.idLines "
                    + "INNER JOIN loandetails loan on cus.loanDetails_idloanDetails = loan.idloanDetails "
                    + "INNER JOIN date d on loan.date_iddate = d.iddate "
                    + "INNER JOIN amount am ON loan.amount_idamount = am.idamount "
                    + "INNER JOIN employees emp ON cus.Employees_idEmployees = emp.idEmployees "
                    + "WHERE cus.nic = '" + txtNic.getSelectedItem().toString() + "'";
            ResultSet rs_02 = databaseConfig.getStatement().executeQuery(sql);

            if (rs_02.first()) {

                txtFirstName.setText(rs_02.getString("firstName"));
                txtLastName.setText(rs_02.getString("lastName"));
                txtAddress.setText(rs_02.getString("address"));
                txtTnumber.setText(rs_02.getString("contactNumber"));
                txtLineName.setSelectedItem(rs_02.getString("lineName"));
                j_d_c_Date.setDate(allConfigIsHere.getDateFormat().parse(rs_02.getString("startDate")));
                txtRental.setSelectedItem(rs_02.getString("rental"));
                kbxAgent.setSelectedItem(rs_02.getString("name"));

            }

        } catch (Exception e) {
            System.out.println(e);
            e.printStackTrace();
        }


    }//GEN-LAST:event_txtNicActionPerformed

    private void txtNicKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNicKeyReleased


    }//GEN-LAST:event_txtNicKeyReleased

    private void txtNicItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txtNicItemStateChanged

    }//GEN-LAST:event_txtNicItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertCustomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertCustomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertCustomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertCustomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertCustomers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JDateChooser j_d_c_Date;
    private javax.swing.JComboBox kbxAgent;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JComboBox txtLineName;
    private javax.swing.JComboBox txtNic;
    private javax.swing.JComboBox txtRental;
    private javax.swing.JTextField txtTnumber;
    // End of variables declaration//GEN-END:variables
}
