/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package daily_investment.Interfaces;

import Class_Files.MessageIcons;
import java.awt.Color;
import java.awt.Toolkit;

/**
 *
 * @author Ishan Darshana
 */
public class Menu extends javax.swing.JFrame {

    static Menu menuObject;
    MessageIcons messageIcons = new MessageIcons();

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource(messageIcons.getFrameIcon())));
        Customer_Panel.setVisible(false);
        Employee_Panel.setVisible(false);
        Report_Panel.setVisible(false);
        Report_Summary.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        B_Collection = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        B_Report = new javax.swing.JButton();
        B_Emp = new javax.swing.JButton();
        B_Sum = new javax.swing.JButton();
        Customer_Panel = new Panel_Customers();
        Employee_Panel = new Panel_Employes();
        Report_Summary = new Panel_Summary();
        Report_Panel = new Panel_Report();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mandakini Investment");
        setResizable(false);
        getContentPane().setLayout(null);

        B_Collection.setBackground(new java.awt.Color(0, 0, 0));
        B_Collection.setFont(new java.awt.Font("Segoe UI Light", 1, 30)); // NOI18N
        B_Collection.setForeground(new java.awt.Color(255, 255, 255));
        B_Collection.setText("COLLECTION");
        B_Collection.setBorderPainted(false);
        B_Collection.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        B_Collection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                B_CollectionMouseEntered(evt);
            }
        });
        B_Collection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_CollectionActionPerformed(evt);
            }
        });
        getContentPane().add(B_Collection);
        B_Collection.setBounds(960, 190, 250, 70);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI Light", 1, 25)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("BACKUP");
        jButton2.setBorderPainted(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setMaximumSize(new java.awt.Dimension(219, 49));
        jButton2.setPreferredSize(null);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(30, 560, 250, 40);

        B_Report.setBackground(new java.awt.Color(0, 0, 0));
        B_Report.setFont(new java.awt.Font("Segoe UI Light", 1, 30)); // NOI18N
        B_Report.setForeground(new java.awt.Color(255, 255, 255));
        B_Report.setText("REPORTS");
        B_Report.setBorderPainted(false);
        B_Report.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        B_Report.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                B_ReportMouseEntered(evt);
            }
        });
        B_Report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_ReportActionPerformed(evt);
            }
        });
        getContentPane().add(B_Report);
        B_Report.setBounds(960, 270, 250, 70);

        B_Emp.setBackground(new java.awt.Color(0, 0, 0));
        B_Emp.setFont(new java.awt.Font("Segoe UI Light", 1, 30)); // NOI18N
        B_Emp.setForeground(new java.awt.Color(255, 255, 255));
        B_Emp.setText("EMPLOYEES");
        B_Emp.setBorderPainted(false);
        B_Emp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        B_Emp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                B_EmpMouseEntered(evt);
            }
        });
        B_Emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_EmpActionPerformed(evt);
            }
        });
        getContentPane().add(B_Emp);
        B_Emp.setBounds(960, 110, 250, 70);

        B_Sum.setBackground(new java.awt.Color(0, 0, 0));
        B_Sum.setFont(new java.awt.Font("Segoe UI Light", 1, 30)); // NOI18N
        B_Sum.setForeground(new java.awt.Color(255, 255, 255));
        B_Sum.setText("SUMMERY");
        B_Sum.setBorderPainted(false);
        B_Sum.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        B_Sum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                B_SumMouseEntered(evt);
            }
        });
        B_Sum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_SumActionPerformed(evt);
            }
        });
        getContentPane().add(B_Sum);
        B_Sum.setBounds(960, 350, 250, 70);

        Customer_Panel.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(Customer_Panel);
        Customer_Panel.setBounds(640, 40, 40, 40);

        Employee_Panel.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(Employee_Panel);
        Employee_Panel.setBounds(640, 130, 40, 40);

        Report_Summary.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(Report_Summary);
        Report_Summary.setBounds(600, 360, 40, 40);

        Report_Panel.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(Report_Panel);
        Report_Panel.setBounds(650, 290, 40, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 35)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("INVESTMENT");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(240, 15, 320, 100);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 35)); // NOI18N
        jLabel3.setText("MANDAKINI");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 0, 310, 130);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI Light", 1, 30)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("CUSTOMERS");
        jButton3.setBorderPainted(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(960, 30, 250, 70);

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI Light", 1, 30)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("SHUT DOWN");
        jButton4.setBorderPainted(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setPreferredSize(null);
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(30, 510, 250, 40);

        setSize(new java.awt.Dimension(1285, 671));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void B_CollectionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_CollectionMouseEntered

        Customer_Panel.setVisible(false);
        Employee_Panel.setVisible(false);
        Report_Summary.setVisible(false);
        Report_Panel.setVisible(false);

    }//GEN-LAST:event_B_CollectionMouseEntered

    private void B_CollectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_CollectionActionPerformed
        new Collection().setVisible(true);
        Menu.menuObject.dispose();
    }//GEN-LAST:event_B_CollectionActionPerformed

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered

    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    }//GEN-LAST:event_jButton2ActionPerformed

    private void B_ReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_ReportMouseEntered

        Customer_Panel.setVisible(false);
        Employee_Panel.setVisible(false);
        Report_Summary.setVisible(false);
        Report_Panel.setVisible(true);
    }//GEN-LAST:event_B_ReportMouseEntered

    private void B_ReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_ReportActionPerformed

    }//GEN-LAST:event_B_ReportActionPerformed

    private void B_EmpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_EmpMouseEntered
        Customer_Panel.setVisible(false);
        Employee_Panel.setVisible(true);
        Report_Summary.setVisible(false);
        Report_Panel.setVisible(false);

    }//GEN-LAST:event_B_EmpMouseEntered

    private void B_EmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_EmpActionPerformed

    }//GEN-LAST:event_B_EmpActionPerformed

    private void B_SumMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_SumMouseEntered
        Customer_Panel.setVisible(false);
        Employee_Panel.setVisible(false);
        Report_Summary.setVisible(true);
        Report_Panel.setVisible(false);
    }//GEN-LAST:event_B_SumMouseEntered

    private void B_SumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_SumActionPerformed

    }//GEN-LAST:event_B_SumActionPerformed

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
        Customer_Panel.setVisible(true);
        Employee_Panel.setVisible(false);
        Report_Summary.setVisible(false);
        Report_Panel.setVisible(false);
    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseEntered

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                menuObject = new Menu();
                menuObject.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Collection;
    private javax.swing.JButton B_Emp;
    private javax.swing.JButton B_Report;
    private javax.swing.JButton B_Sum;
    private javax.swing.JPanel Customer_Panel;
    private javax.swing.JPanel Employee_Panel;
    private javax.swing.JPanel Report_Panel;
    private javax.swing.JPanel Report_Summary;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
